// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb, defaultTargetPlatform, TargetPlatform;

// Default FirebaseOptions for use with your Firebase apps.
//
// Example:
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';
//
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: "AIzaSyBESXQnbJ8Lf5Jp5omAOdQ4_ps_0xglAtE",
        appId: "1:764584401192:web:abcdef123456789",
        messagingSenderId: "764584401192",
        projectId: "service-app-f7e8e",
        storageBucket: "service-app-f7e8e.firebasestorage.app",
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: "AIzaSyBESXQnbJ8Lf5Jp5omAOdQ4_ps_0xglAtE",
          appId: "1:764584401192:android:44d528fe62541f1507181d",
          messagingSenderId: "764584401192",
          projectId: "service-app-f7e8e",
          storageBucket: "service-app-f7e8e.firebasestorage.app",
        );
      case TargetPlatform.iOS:
        return const FirebaseOptions(
          apiKey: "AIzaSyBESXQnbJ8Lf5Jp5omAOdQ4_ps_0xglAtE",
          appId: "1:764584401192:ios:abcdef123456",
          messagingSenderId: "764584401192",
          projectId: "service-app-f7e8e",
          storageBucket: "service-app-f7e8e.firebasestorage.app",
          iosBundleId: "com.service.app",
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
